name: dl4phys
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - cudatoolkit=11.3
  - pip
  - notebook
  - ipykernel
  - ipywidgets
  - git-lfs
  - pip:
      - -r requirements.txt
